name: CI/CD flow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t arslan173/usermanagement:latest .
      - name: Publish image to docker hub
        run: docker push arslan173/usermanagement:latest

  deploy:
    needs: build
    runs-on: [self-hosted]
    steps:
      - name: Pull Image from Docker Hub
        run: docker pull arslan173/usermanagement:latest

      - name: Stop and Remove Old Container
        run: docker rm -f usermanagement-container

      - name: Run Docker Container
        run: docker run -d --network host --name usermanagement-container arslan173/usermanagement:latest

      - name: Clean Up Old Docker Images
        run: docker image prune -f
#        run: docker system prune