name: CI/CD flow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t arslan173/usermanagement:latest .

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Stop and Remove Old Container
        run:
          docker stop usermanagement-container || true
          docker rm usermanagement-container || true

      - name: Pull Image from Docker Hub
        run: docker pull arslan173/usermanagement:latest

      - name: Run Docker Container
        run: docker run -d --network host --name usermanagement-container arslan173/usermanagement:latest

